node {
    deleteDir()
    APP_NAME="ugb-processor"
    RESOURCE_NAME="ugb-processor"
    NAMESPACE="default"

    try {
        stage ('Checkout') {
        	checkout scm
        }

//         if (env.BRANCH_NAME == 'master'){
            stage ('go get dependencies') {
				sh 'go get'
            }
            stage ('go build') {
				sh 'go build -o ugb-processor'
            }

            stage ('Build Image') {
				sh "docker build -t hub.tisserv.net/$RESOURCE_NAME:v${env.BUILD_NUMBER} ."
            }

      	    stage ('Push&Clean Image') {
				sh "docker push hub.tisserv.net/$RESOURCE_NAME:v${env.BUILD_NUMBER}"
				sh "docker rmi -f hub.tisserv.net/$RESOURCE_NAME:v${env.BUILD_NUMBER}"
		}

           stage ('deploy') {
               sh '''
                   cd infra

                   terraform init
                   terraform validate .
                   terraform plan -var DOCKER_IMG_TAG=v${BUILD_NUMBER}
                   terraform apply -var DOCKER_IMG_TAG=v${BUILD_NUMBER} -auto-approve
               '''
           }
//         }
    } catch (err) {
        throw err
    }
}
